name: "Ddosify Latency Testing"

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  latency-test:
    runs-on: ubuntu-latest

    steps:
    - name: Ddosify Latency Test
      uses: ddosify/ddosify-latency-action@master
      with:
        api_key: ${{ secrets.DDOSIFY_API_KEY }}
        target: "https://app.servdown.com"
        locations: '["*"]'
        failIf: "EU.*>100"
