name: "Ddosify Latency Testing"

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  latency-test:
    runs-on: ubuntu-latest

    steps:
    - name: Ddosify Latenct Test
      uses: ddosify/ddosify-latency-action@master
      with:
        api_key: ${{ secrets.DDOSIFY_API_KEY }}
        target: "https://app.servdown.com"
